version: '2'

services:

  kafka:
    image: treelogic:kafka
    hostname: kafka
    container_name: kafka
    domainname: proteus
    volumes:
      - ./proteus-data/coiltimeseries_data:/opt/proteus-dataset
    networks: 
      - proteus

  zookeeper:
    image: treelogic:zookeeper
    hostname: zookeeper
    container_name: zookeeper
    domainname: proteus
    networks: 
      - proteus

  logs:
    image: treelogic:logs
    hostname: logs
    container_name: logs
    domainname: proteus
    networks:
      - proteus

  data:
    image: treelogic:data
    hostname: data
    container_name: data
    domainname: proteus
    networks:
      - proteus
    volumes:
      - ./Dataset/:/proteus-coiltimeseries/

networks:
  proteus:
    driver: bridge
